config/routes.rb
Rails.application.routes.draw do

  root 'store#index', as: 'store'

  resources :items, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :users, only: [:show]
  resources :carts
  resources :line_items, only: [:create]
  resources :orders, only: [:show]

  post 'carts/:id/checkout', to: 'carts#checkout', as: 'checkout'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_many :items, through: :line_items

  def add_item(item_id)
    current_item = self.line_items.find_by(item_id: item_id) 
    if current_item
      current_item.quantity += 1
    else
      current_item = self.line_items.build(item_id: item_id)
    end
    current_item
  end

  def total
    total = 0
    self.line_items.each do |line_item|
      total += line_item.item.price * line_item.quantity
    end
    return total
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :line_items

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :item 
  belongs_to :cart
end

app/models/order.rb
class Order < ActiveRecord::Base  
  belongs_to :cart
  has_many :items, through: :cart

  def self.create_from_cart(cart)
    self.create(
      cart_id: cart.id,
      total: cart.total
    )
  end

  def change_order_status
    self.update(status: "submitted") 
  end

  def change_inventory
    if self.status = "submitted"
      self.cart.line_items.each do |line_item| 
        line_item.item.inventory -= line_item.quantity
        line_item.item.save
      end
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def initialize_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end

  def current_cart
    @current_cart ||= Cart.find(session[:cart_id]) if session[:cart_id]
  end
  helper_method :current_cart
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :set_cart, only: [:checkout, :show]

  def show
  end

  def checkout
    @order = Order.create_from_cart(@cart)
    @order.change_order_status
    @order.change_inventory
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to order_path(@order), notice: 'Thanks for your order!' }
    end
  end

  private
  def set_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :set_category, only: [:show]

  def index
    @categories = Category.all
  end

  def show
  end

  private
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :set_item, only: [:show]

  def index
    @items = Item.all
  end

  def show
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :initialize_cart, only: [:create]

  def create
    item = Item.find(params[:item_id])
    @line_item = current_cart.add_item(item.id)
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to cart_path(current_cart),
        notice: 'Item added to cart!' }
      else
        redirect_to store_path
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end
  
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
    @items = Item.order(:title)
    @categories = Category.order(:title)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
  def to_currency(num)
    num.to_f / 100
  end
end

app/views/carts/show.html.erb
<div class="container">
  <% if notice %>
    <div class="alert alert-success" role="alert"><%= notice %></div>
  <% end %>
  <div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <h2>Your Cart</h2>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th class="text-center">Price</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
      <% current_cart.line_items.each do |line_item| %>
        <tbody>
          <tr>
            <td class="col-sm-8 col-md-6">
              <h4 class="media-heading"><%= link_to line_item.item.title, item_path(line_item.item) %></h4>
            </td>
            <td class="col-sm-1 col-md-1" style="text-align: center">
            <input type="text" class="form-control" id="exampleInputEmail1" value="<%= line_item.quantity %>" data-id="<%= line_item.id %>">
            </td>
            <td class="col-sm-1 col-md-1 text-center" id="price"><%= number_to_currency(to_currency(line_item.item.price)) %></td>
            <td class="col-sm-1 col-md-1 text-center" id="sub-total"><%= number_to_currency(to_currency(line_item.quantity * line_item.item.price)) %></td>
            <td>
            </td>
          </tr>
      <% end %>
            <tr>
              <td>   </td>
              <td>   </td>
              <td>   </td>
              <td><h3>Total</h3></td>
              <td class="text-right"><h3 class="total"><strong><strong><%= number_to_currency(to_currency(current_cart.total)) %></strong></h3></td>
            </tr>
            <tr>
              <td>   </td>
              <td>   </td>
              <td>   </td>
              <td>
              <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span><%= link_to " Continue Shopping", store_path %>
              </button></td>
              <td id="stripe-button">
                <%= render 'carts/stripe_modal' %>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
<ul>
    <li>
  <%= link_to category.title, category_path(category) %>
    </li>
</ul>
<% end %>

app/views/categories/show.html.erb
<div class="container">
  <h1><%= @category.title %></h1>
  <% @category.items.each do |item| %>
    <ul>
      <li><%= link_to item.title, item_path(item) %> | <strong><%= number_to_currency(to_currency(item.price)) %></strong> <%= button_to 'Add to Cart', line_items_path(item_id: item), class: "btn btn-primary" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
<h2><%= number_to_currency(to_currency(@item.price)) %></h2>
<%= button_to 'Add to Cart', line_items_path(item_id: @item), class: "btn btn-primary" %>

app/views/layouts/_header.html.erb
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
          <h1 class="muted">Flatiron Store</h1>
          <button type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-arrow-left"></span><%= link_to " Store Home", store_path %>
          </button> 
          <div class="btn-group btn-group-default">
          <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-th"><%= link_to " Categories", categories_path %></button>
          <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button"><span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.title, category_path(category) %></li>
            <% end %>
          </ul>
          </div>
          <% if current_cart %>
            <button type="button" class="btn btn-default">
              <span class="glyphicon glyphicon-shopping-cart"></span><%= link_to " Cart", cart_path(current_cart) %>
            </button>
          <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsFlatironStore</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/orders/show.html.erb
<div class="container">
  <% if notice %>
      <div class="alert alert-success" role="alert"><%= notice %></div>
    <% end %>

  <h1>Thank you!</h1>
  <h2>Order status: <%= @order.status %></h2>
  <h3>You paid: <strong><%= number_to_currency(to_currency(@order.total)) %></strong></h3>
</div>

app/views/store/index.html.erb
<div class="container">
  <% @items.each do |item| %>
    <%= link_to item.title, item_path(item) %> | <strong><%= number_to_currency(to_currency(item.price)) %></strong><span><%= button_to 'Add to Cart', line_items_path(item_id: item), class: "btn btn-primary" %></span>
  <% end %>
</div>